/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-02-07 08:55:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;

public final class SearchBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/SearchBookMessage.jsp", Long.valueOf(1707221317658L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Search book Page</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"indexStyle.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <h1>e-Library Management System</h1>\r\n");
      out.write("                ");
      out.write('\r');
      out.write('\n');

   List list = (List)session.getAttribute("message1");
	if(list != null){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"table table-striped table-hover\">\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr class=\"table-dark\">\r\n");
      out.write("      <th scope=\"col\">Book id</th>\r\n");
      out.write("      <th scope=\"col\">title</th>\r\n");
      out.write("      <th scope=\"col\">Author</th>\r\n");
      out.write("      <th scope=\"col\">cost</th>\r\n");
      out.write("      <th scope=\"col\">Quantity</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("    <tr class=\"table-dark\">\r\n");
      out.write("      <th scope=\"row\">");
      out.print( list.get(0) );
      out.write("</th>\r\n");
      out.write("      <td>");
      out.print( list.get(1) );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print( list.get(4) );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print( list.get(2) );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print( list.get(3) );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
	
		session.removeAttribute("message1");
	}else{	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("  <strong>The book not exist</strong> \r\n");
      out.write("  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");
 
	session.removeAttribute("message1");
	}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container text-center\" id=\"container3Part2\">\r\n");
      out.write("                <div class=\"row justify-content-around\">\r\n");
      out.write("                    <div class=\"col-2\">\r\n");
      out.write("                        <a class=\"btn btn-primary\" id=\"mainBookPage\" href=\"AddBooks.jsp\" role=\"button\">\r\n");
      out.write("                            <h6>Add Book</h6>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-2\">\r\n");
      out.write("                        <a class=\"btn btn-primary\" id=\"mainBookPage\" href=\"SearchBook.jsp\" role=\"button\">\r\n");
      out.write("                            <h6>Book Search</h6>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-2\">\r\n");
      out.write("                        <a class=\"btn btn-primary\" id=\"mainBookPage\" href=\"BookUpdate.jsp\" role=\"button\">\r\n");
      out.write("                            <h6>Book Update</h6>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-2\">\r\n");
      out.write("                        <a class=\"btn btn-primary\" id=\"mainBookPage\" href=\"ViewOrder.jsp\" role=\"button\">\r\n");
      out.write("                            <h6>View Order</h6>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-2\">\r\n");
      out.write("                        <a class=\"btn btn-primary\" id=\"mainBookPage\" href=\"AdminSignout.jsp\" role=\"button\">\r\n");
      out.write("                            <h6>Signout</h6>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cotainer\" id=\"container3Part2\">\r\n");
      out.write("                <div class=\"row justify-content-evenly\">\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <img src=\"https://s3-alpha-sig.figma.com/img/ed57/72b9/ccf70f553c94ca56156e63323c6ea104?Expires=1707696000&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=NTiCeGVbrUmawkb4q5BYvFre4duXA-3MpRiLxEw~mp1AJxqgT43BxEot7SZw8KjRKthGpk-H-5MIMOuhdQ~j1tpRjBKz2QGoy-U7112Th36wfq5AX9UB-J7ExT0SDdE8nL1gl3yXuIEp2VozPxxobh1gpGeHaocKgCVfNAwq8khf6q10PSy-dp0UKzqoB66CRG2ggI3zW9OvZscbr7HECzPo07ppfFIa-JBtarHaHNsGe31HuJXLSrIlmcvC3rmUgdzrDDzpkojdZEDr8LawowT2q7logmOE0lPYEkARlkG-YUurbfbp-en-~4KCRwLgwQXBSyXateONcJA3WTNodA__\"\r\n");
      out.write("                            id=\"leftImg\" alt=\"Img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <form action = \"SearchBooks\" method = \"post\">\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"inputBookid3\" class=\"col-sm-2 col-form-label\">Book Id</label>\r\n");
      out.write("                                <div class=\"col-sm-10\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"inputBookid3\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary\">Search</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
